In [33]:
import numpy as np

In [34]:
%%time
N=100000000
normlList=list(range(N))
for i in range(N):
    normlList[i]=normlList[i]**2

Wall time: 41.6 s


In [35]:
%%time
normlList=list(range(N))
normlList = [item * item for item in normlList]

Wall time: 9.78 s


In [36]:
%%time
normlList=list(range(N))
normlList=map(lambda x: x*x, normlList)

Wall time: 2.35 s


In [37]:
%%time
arr = np.arange(N)
arr = arr * arr

Wall time: 212 ms


In [38]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

Wall time: 151 ms


In [39]:
#creating array
arr = np.arange(5)
print(arr, type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [40]:
#creating arrray from list
arr = np.array([[1,2,3,4,5],
                [4,6,8,0,2]])
print(arr, type(arr))

[[1 2 3 4 5]
 [4 6 8 0 2]] <class 'numpy.ndarray'>


In [41]:
#array parameters
print(arr.dtype,arr.ndim,arr.size, arr.shape, arr.itemsize)

int32 2 10 (2, 5) 4


In [42]:
np.random.randn(2,3) #mean=0 variance=1, n denotes normal distribution

array([[ 0.57203782, -2.70137848,  0.89387826],
       [ 0.42233973, -0.54178237, -0.76645908]])

In [43]:
np.random.randint(0,100,(3,4))

array([[12, 34, 59, 46],
       [71, 10, 46, 57],
       [34, 16, 99, 60]])

In [44]:
np.arange(1,10,2)   #last value is stepsize

array([1, 3, 5, 7, 9])

In [45]:
np.linspace(7,65,10)   #generates array with last value as size

array([ 7.        , 13.44444444, 19.88888889, 26.33333333, 32.77777778,
       39.22222222, 45.66666667, 52.11111111, 58.55555556, 65.        ])

In [46]:
str_arr = np.array(['1.4','5.9','2.0'])      #coool
arr = np.array(str_arr, dtype='float')
arr

array([1.4, 5.9, 2. ])